#!/usr/bin/env bun
// Wave 5 certification remediation -- DETERMINISTIC metadata twin for the positional dataset.
//
// data/metadata/hero-positions.json must describe apps/engine/src/signals/hero-positions.json
// truthfully: every field here is either copied verbatim from the dataset's own embedded
// provenance, or mechanically computed from its rows (hero count, observation/below-floor row
// counts, population sums, sha256). Nothing is hand-authored -- a field that cannot be derived
// truthfully from the dataset is left `null`, never invented.
//
//   bun scripts/positions/metadata-twin.ts [--dataset=<path>] [--out=<path>]
//   bun scripts/positions/metadata-twin.ts --check    (no write; exits 1 if the twin on disk has drifted)
//
// Regenerates purely from the already-frozen dataset file -- no STRATZ_API_KEY, no network, no
// raw STRATZ payload required. Same input bytes -> same output bytes: no clock, no randomness.
// `generatedAt` is intentionally null (this is a pure re-derivation, not a fresh collection) --
// see `generatedAtNote`. Never imported from apps/. Zero network.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { HERO_POSITION_OBSERVATIONS_SCHEMA } from "../../apps/engine/src/signals/hero-positions";

export const METADATA_TWIN_GENERATOR = "scripts/positions/metadata-twin.ts@1";
export const LEGACY_FORMAT = "v1-floor-truncated";

export interface PopulationSummary {
  totalPopulationMatches: number;
  totalKnownPositionMatches: number;
  totalUnassignedMatches: number;
  /** Recomputed independently from `heroes[]` and compared against the dataset's own claimed totals (when present). */
  identityVerifiedAgainstProvenance: boolean;
}

export interface PositionsMetadataTwin {
  path: string;
  sha256: string;
  schema: string | null;
  format: typeof HERO_POSITION_OBSERVATIONS_SCHEMA | typeof LEGACY_FORMAT;
  denominatorCorrected: boolean;
  source: string | null;
  bracketClaim: string | null;
  gameMode: string | null;
  patchClaim: unknown | null;
  rulesetTarget: string | null;
  /** Generic data/metadata contract field (ADR-003) -- best available patch label; see `patchClaim` for its verification status. */
  patch: string | null;
  retrievedAt: unknown | null;
  selectedBucketIds: number[] | null;
  bucketSelection: unknown | null;
  completeness: string | null;
  completenessEvidence: unknown | null;
  admissionFloorMatches: number | null;
  datasetGenerator: string | null;
  rawSnapshotSha256: string | null;
  heroCount: number;
  observationRowCount: number;
  belowFloorRowCount: number;
  population: PopulationSummary | null;
  generatedAt: null;
  generatedAtNote: string;
  generatorVersion: string;
  rowCount: number;
  schemaVersion: 1;
  sampleWindow: null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

interface RawObservationHero {
  hero?: unknown;
  totalPopulationMatches?: unknown;
  totalKnownPositionMatches?: unknown;
  unassignedMatches?: unknown;
  observations?: unknown;
}

/**
 * Pure: builds the twin from already-read dataset bytes. Never touches disk -- callers own I/O
 * (main() below); tests inject fixture bytes directly (S9/S10 convention: a curated file that is
 * regenerated by parch/collection can never be the substrate of a test).
 */
export function buildPositionsMetadataTwin(datasetPath: string, datasetBytes: Uint8Array): PositionsMetadataTwin {
  const sha256 = createHash("sha256").update(datasetBytes).digest("hex");
  const raw: unknown = JSON.parse(Buffer.from(datasetBytes).toString("utf8"));

  if (Array.isArray(raw)) {
    const observationRowCount = raw.reduce(
      (sum: number, entry: unknown) => sum + (isRecord(entry) && Array.isArray(entry.positions) ? entry.positions.length : 0),
      0,
    );
    return {
      path: datasetPath,
      sha256,
      schema: null,
      format: LEGACY_FORMAT,
      denominatorCorrected: false,
      source: null,
      bracketClaim: null,
      gameMode: null,
      patchClaim: null,
      rulesetTarget: null,
      patch: null,
      retrievedAt: null,
      selectedBucketIds: null,
      bucketSelection: null,
      completeness: null,
      completenessEvidence: null,
      admissionFloorMatches: null,
      datasetGenerator: null,
      rawSnapshotSha256: null,
      heroCount: raw.length,
      observationRowCount,
      belowFloorRowCount: 0, // the legacy collector already discarded sub-floor rows -- unknowable from this file alone
      population: null,
      generatedAt: null,
      generatedAtNote: "legacy v1-floor-truncated dataset carries no per-hero population identity to derive from",
      generatorVersion: METADATA_TWIN_GENERATOR,
      rowCount: raw.length,
      schemaVersion: 1,
      sampleWindow: null,
    };
  }

  if (!isRecord(raw) || !Array.isArray(raw.heroes)) {
    throw new Error(`${datasetPath}: unrecognized dataset shape -- expected an array (legacy) or an object with a "heroes" array`);
  }

  const provenance = isRecord(raw.provenance) ? raw.provenance : {};
  const heroes = raw.heroes as RawObservationHero[];
  const admissionFloorMatches = typeof provenance.admissionFloorMatches === "number" ? provenance.admissionFloorMatches : null;

  let observationRowCount = 0;
  let belowFloorRowCount = 0;
  let totalPopulationMatches = 0;
  let totalKnownPositionMatches = 0;
  let totalUnassignedMatches = 0;
  let sawPopulationFields = heroes.length > 0;

  for (const hero of heroes) {
    const observations = Array.isArray(hero.observations) ? hero.observations : [];
    observationRowCount += observations.length;
    for (const obs of observations) {
      if (isRecord(obs) && typeof obs.matches === "number" && admissionFloorMatches !== null && obs.matches < admissionFloorMatches) {
        belowFloorRowCount += 1;
      }
    }
    if (
      typeof hero.totalPopulationMatches === "number" &&
      typeof hero.totalKnownPositionMatches === "number" &&
      typeof hero.unassignedMatches === "number"
    ) {
      totalPopulationMatches += hero.totalPopulationMatches;
      totalKnownPositionMatches += hero.totalKnownPositionMatches;
      totalUnassignedMatches += hero.unassignedMatches;
    } else {
      sawPopulationFields = false;
    }
  }

  const completenessEvidence = isRecord(provenance.completenessEvidence) ? provenance.completenessEvidence : null;
  const identityVerifiedAgainstProvenance =
    sawPopulationFields &&
    completenessEvidence !== null &&
    completenessEvidence.totalPopulationMatches === totalPopulationMatches &&
    completenessEvidence.totalKnownPositionMatches === totalKnownPositionMatches &&
    completenessEvidence.unassignedMatches === totalUnassignedMatches;

  return {
    path: datasetPath,
    sha256,
    schema: typeof raw.schema === "string" ? raw.schema : null,
    format: HERO_POSITION_OBSERVATIONS_SCHEMA,
    denominatorCorrected: true,
    source: typeof provenance.source === "string" ? provenance.source : null,
    bracketClaim: typeof provenance.bracketClaim === "string" ? provenance.bracketClaim : null,
    gameMode: typeof provenance.gameMode === "string" ? provenance.gameMode : null,
    patchClaim: provenance.patchClaim ?? null,
    rulesetTarget: typeof provenance.rulesetTarget === "string" ? provenance.rulesetTarget : null,
    patch: typeof provenance.rulesetTarget === "string" ? provenance.rulesetTarget : null,
    retrievedAt: provenance.retrievedAt ?? null,
    selectedBucketIds: Array.isArray(provenance.selectedBucketIds) ? provenance.selectedBucketIds : null,
    bucketSelection: provenance.bucketSelection ?? null,
    completeness: typeof provenance.completeness === "string" ? provenance.completeness : null,
    completenessEvidence,
    admissionFloorMatches,
    datasetGenerator: typeof provenance.generator === "string" ? provenance.generator : null,
    rawSnapshotSha256: typeof provenance.rawSnapshotSha256 === "string" ? provenance.rawSnapshotSha256 : null,
    heroCount: heroes.length,
    observationRowCount,
    belowFloorRowCount,
    population: sawPopulationFields
      ? { totalPopulationMatches, totalKnownPositionMatches, totalUnassignedMatches, identityVerifiedAgainstProvenance }
      : null,
    generatedAt: null,
    generatedAtNote:
      "pure re-derivation of the dataset's own provenance + mechanically counted rows -- no wall-clock timestamp, so two runs over the same dataset are byte-identical",
    generatorVersion: METADATA_TWIN_GENERATOR,
    rowCount: heroes.length,
    schemaVersion: 1,
    sampleWindow: null,
  };
}

export function serializeTwin(twin: PositionsMetadataTwin): string {
  return `${JSON.stringify(twin, null, 2)}\n`;
}

/**
 * Pure drift check: does the twin text already on disk match what the generator would produce
 * right now, from these exact dataset bytes? Used by both `--check` and its test.
 */
export function checkSync(
  datasetPath: string,
  datasetBytes: Uint8Array,
  existingTwinText: string | null,
): { inSync: boolean; twin: PositionsMetadataTwin; expectedText: string } {
  const twin = buildPositionsMetadataTwin(datasetPath, datasetBytes);
  const expectedText = serializeTwin(twin);
  return { inSync: existingTwinText === expectedText, twin, expectedText };
}

function arg(name: string): string | undefined {
  return process.argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);
}

export function main(): number {
  const ROOT = resolve(import.meta.dir, "../..");
  const datasetPath = arg("dataset") ?? "apps/engine/src/signals/hero-positions.json";
  const outPath = arg("out") ?? "data/metadata/hero-positions.json";
  const check = process.argv.includes("--check");

  const datasetBytes = readFileSync(resolve(ROOT, datasetPath));
  const outTarget = resolve(ROOT, outPath);

  if (check) {
    const existingTwinText = existsSync(outTarget) ? readFileSync(outTarget, "utf8") : null;
    const result = checkSync(datasetPath, datasetBytes, existingTwinText);
    if (!result.inSync) {
      console.error(
        existingTwinText === null
          ? `${outPath} does not exist -- run without --check to generate it`
          : `${outPath} is out of sync with ${datasetPath} -- regenerate with: bun scripts/positions/metadata-twin.ts`,
      );
      return 1;
    }
    console.log(`${outPath} matches ${datasetPath} (sha256 ${result.twin.sha256})`);
    return 0;
  }

  const twin = buildPositionsMetadataTwin(datasetPath, datasetBytes);
  const text = serializeTwin(twin);
  mkdirSync(dirname(outTarget), { recursive: true });
  writeFileSync(outTarget, text);
  console.log(
    JSON.stringify(
      {
        wrote: outPath,
        sha256: twin.sha256,
        heroCount: twin.heroCount,
        observationRowCount: twin.observationRowCount,
        belowFloorRowCount: twin.belowFloorRowCount,
        denominatorCorrected: twin.denominatorCorrected,
      },
      null,
      2,
    ),
  );
  return 0;
}

if (import.meta.main) process.exit(main());
